### ISSUE TITLE
Development: Bootstrapping PrairieLearn Scripting

### ISSUE THREAD

**Issue by andrewstec** [ubccpsctech/PrairieLearn#1]
PrairieLearn needs to be bootstrapped on Linux RHEL 7.7 (x86_64) on the Students domain. A staging ground exists where the application may be setup.

Install and Configure Dependencies: 

- Postgres
- Node JS
- PrairieLearn application

Technical Requirements: 

- The native version should be installed (not running inside a Docker container)
- Determine user account and security configuration requirements for Postgres
- Ensure that Postgres can only be accessed from localhost with VM IP bind
- PostgreSQL v11.6
  - PGDG Repo: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  - EPEL Repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
- Postgres is installed as a system service with `systemctl`
- Node v12.13.1
  - yum install gcc-c++ make (to support builds)
  - curl -sL https://rpm.nodesource.com/setup_11.x | bash -
- Determine and install PrairieLearn dependencies (such as Git)
- Have configuration override file brought into application from script to ensure it is not committed as code
- PL application source: https://github.com/ubccpsctech/PrairieLearn.git

Requirements:

- Deliver a bash script that documents the configuration setup for Postgres, Node, and PrairieLearn that results in application ready for production.

Acceptance Criteria: 

- User can login to Postgres through console
- Application starts-up
- Application can login to Postgres and create a database
- User can authenticate to application
- When user authenticates, user is found in the database with the appropriate data under the user row
- Postgres starts as service

**Comment by andrewstec** [comment]
Supporting Links: 

https://yum.postgresql.org/repopackages.php#pg11

**Comment by andrewstec** [comment]
** Should use official RHEL packages for first installation round **, which affects Postgres and Node JS versions listed above. They will be slightly lower versions.

If we decide to upgrade to other Postgres and Node JS versions, we can implement that after we decide that is the way to go.

**Comment by andrewstec** [comment]
Database scripting done here: https://github.com/ubccpsctech/PrairieLearn/issues/5.

**Comment by andrewstec** [comment]
Removed requirements because they are out of scope: 

```
Install Python marking dependencies with instructions on PL
Ensure that Shib integration results in valid PrairieLearn users
```

- The Python installation is managed in the system setup and placed in a virtual environment
- The Shib integration is managed in the system setup and enabled in our `config.json` file where `hasShib` is true. The `config.json` is automatically produced when bootstrapping PrairieLearn in the `install_prairielearn.sh` script.

**Comment by andrewstec** [comment]
### Update

Three scripts have been written:

- install-nodejs.sh
- install-prairielearn.sh
- install-postgres.sh

They could tentatively be merged into one script if we want to go that route. The script would likely have to become more programmatic to re-use code or else it would get complicated to read.

@winstan Just let me know what you prefer. If you want the scripts to be kept broken-up this way, or merged into one script, either option works for me.

**Comment by winstan** [comment]
Separate is probably better. Postgres is likely to be on a standalone server...

**Comment by andrewstec** [comment]
One thought is that we should consider the SSL setup as well then. Is that something that we want to take a look at right now, or would we want to deal with it when the VM is setup for Postgres?

**Comment by winstan** [comment]
At this point, let's prioritize figuring out PrairieLearn itself. Only work on the surrounding tools if you have to in order to get PL to work.
